### PR TITLE
Make whiteboard-related items fully grouped

### LINKED ISSUE #12672: Whiteboard-related items aren't fully grouped
###### Reproduction Steps

1. "Settings" > "Appearance" > "App bar buttons" 
2. Set all of the items to "Menu only"
3. Go back to Decks screen, and tap any deck
  (then, Study screen of the deck gets shown)
4. "More options" (three dots icon) > "Enable whiteboard"
image

###### Expected Result
The whiteboard-related items are grouped, that is, they lined up in one area.

###### Actual Result
The group of whiteboard-related item is divided by the other items.
image

###### Debug info
```
AnkiDroid Version = 2.16alpha86

Android Version = 11

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = 8d368aeb-897f-40c1-bd7c-b18afe12a517

New schema = true

Scheduler = std3

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by snowtimeglass**
## Purpose / Description
On action menu of Study screen, the group of whiteboard-related item is divided by the other items. This PR is to fix it.
image
## Fixes
Fixes #12672

## Approach
- Move "Undo ~" above "Clear whiteboard"  (i.e. move "Undo ~" to the top of the menu)

- Move "Save whiteboard" and "Disable/Enable whiteboard" above "Flag card" (i.e. move "Flag card" item below the group of whiteboard-related items)

## How Has This Been Tested?
Checked on physical device
image
image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Did you want to merge this into https://github.com/ankidroid/Anki-Android? Or this is only a test inside your branch?

Only noting this because you linked the GH issue on the PR text, so I came here

**Comment by snowtimeglass** [comment]
Ah, thank you for your concern. Yes, I want to merge this into https://github.com/ankidroid/Anki-Android. I seem to have made some mistake. I’ll try to make it right later.

**Review by mikehardy — APPROVED** [review]
Yes - similar to your other change this does make sense, things *should* be grouped - it is hard to disagree with that...

Thanks!

**Comment by mikehardy** [comment]
I think you can just go to the AnkiDroid repo and make the pull there with the same commit from this same branch.

**Comment by snowtimeglass** [comment]
Thank you two. I'll close this PR later.

Could you please teach me one thing? When I'm about to submit a PR and I see a message like "This branch is 1 commit ahead, 8 commits **behind** ankidroid:main", is it OK to submit the PR without updating the branch? Though I updated branches in cases like this, the PRs seem to be unnecessarily complicated as you can see on the timeline above.
image

**Comment by mikehardy** [comment]
In general, it is nearly impossible to keep a branch up to date vs AnkiDroid main branch because we merge so many PRs per day. A branch is out of date almost as soon as it is created! That's normally okay though.

We do not like the merge commits that happen when you click the Update branch button, usually on the command line I "pull upstream main into my branch via rebase" which looks like this as a command, assuming you have the main repository set with remote name "upstream": `git fetch upstream && git rebase upstream/main` - then I repush my now-updated branch with `git push --force-with-lease`, now it is all up to date, but with clean commits

**Comment by mikehardy** [comment]
In the case of the PR you made in the main repo with a merge commit, I just used the "squash merge" style which crunches all of the branch + merge commit history down to a single commit, so it maintains our main repo / main branch linear commit history

**Comment by snowtimeglass** [comment]
Thank you, I'll learn more about PR little by little.

**Pull request closed without merging**
